#ifndef IR_TRACKER_H
#define IR_TRACKER_H



#define DEF_TRACK_ORIENTATION_DEG_0 0
#define DEF_TRACK_ORIENTATION_DEG_90 1
#define DEF_TRACK_ORIENTATION_DEG_180 2
#define DEF_TRACK_ORIENTATION_DEG_270 3


#endif // IR_TRACKER_HPP